GET http://localhost:8000/products/ HTTP/1.1

###
DELETE  http://localhost:8000/products/1/ HTTP/1.1


### 
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MjE1MjIyLCJpYXQiOjE3NTQyMTQ5MjIsImp0aSI6ImQ2MTg2MTBlZTg0NTRkZmI5MmJmZTRlZjIwN2RhYzEyIiwidXNlcl9pZCI6IjIifQ.Xiqw8ZuhKh-xEktNqr9qoTC15k912rihBfZRHZP11pU

{
    "name": "TVv",
    "price": "15",
    "stock": 5
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "mmd",
    "password": "1234qwer"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin2",
    "password": "1234"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NDY0NjQ1NSwiaWF0IjoxNzU0NTYwMDU1LCJqdGkiOiIyZGQ4NDU0NTdiMmI0OTYwODk5ZjY5M2U0NDcxNmIyZSIsInVzZXJfaWQiOiIyIn0.FMpokFex1_u-yFXeKwvXZvdfm0W7cYa3hEm_XzllryA"
}

###
GET http://localhost:8000/orders/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NzY0NTcwLCJpYXQiOjE3NTk3NjQyNzAsImp0aSI6ImZhM2JjMWRmOGNmNzQwYTU5MWM2MDEyNmJjZjM4ZjUwIiwidXNlcl9pZCI6IjMifQ.oBNwgzWFtp5zjAtcY1bwRD_THdHJh8gSDZStGoobDT8

###
GET http://localhost:8000/orders/6febe729-5f01-4f09-a6cf-4e4a0dc0d6da/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNTM2MDAwLCJpYXQiOjE3NjA1MzU3MDAsImp0aSI6ImJlNDY2YTViZDdlMjRhNGJiNDIyMDJmZTgyZWFlMDJiIiwidXNlcl9pZCI6IjIifQ.1dSho9BrPb8liUFT9Vi-orMVInSousVSia_1VWtdcCs

###
POST http://localhost:8000/orders/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNTM1NTM0LCJpYXQiOjE3NjA1MzUyMzQsImp0aSI6ImVmMTU5ZTA5MDA5YTQxMTQ4ODNjNDZjN2ZmOTk1NzcyIiwidXNlcl9pZCI6IjIifQ.yn5nWApnLnDz34XsBcDVXztrTvq23vMeimTP2lLFdX0


{
    "status": "Pending",
    "user": 2, 
    "items": [
        {
            "product": 2,
            "quantity": 3
        },
        {
            "product": 3,
            "quantity": 2
        }
    ]
}

###
DELETE http://localhost:8000/orders/6febe729-5f01-4f09-a6cf-4e4a0dc0d6da/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNTM2MDAwLCJpYXQiOjE3NjA1MzU3MDAsImp0aSI6ImJlNDY2YTViZDdlMjRhNGJiNDIyMDJmZTgyZWFlMDJiIiwidXNlcl9pZCI6IjIifQ.1dSho9BrPb8liUFT9Vi-orMVInSousVSia_1VWtdcCs