GET http://localhost:8000/products/ HTTP/1.1

###
DELETE  http://localhost:8000/products/1/ HTTP/1.1


### 
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MjE1MjIyLCJpYXQiOjE3NTQyMTQ5MjIsImp0aSI6ImQ2MTg2MTBlZTg0NTRkZmI5MmJmZTRlZjIwN2RhYzEyIiwidXNlcl9pZCI6IjIifQ.Xiqw8ZuhKh-xEktNqr9qoTC15k912rihBfZRHZP11pU

{
    "name": "TVv",
    "price": "15",
    "stock": 5
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "mmd",
    "password": "1234qwer"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NDY0NjQ1NSwiaWF0IjoxNzU0NTYwMDU1LCJqdGkiOiIyZGQ4NDU0NTdiMmI0OTYwODk5ZjY5M2U0NDcxNmIyZSIsInVzZXJfaWQiOiIyIn0.FMpokFex1_u-yFXeKwvXZvdfm0W7cYa3hEm_XzllryA"
}

###
GET http://localhost:8000/orders/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NzY0NTcwLCJpYXQiOjE3NTk3NjQyNzAsImp0aSI6ImZhM2JjMWRmOGNmNzQwYTU5MWM2MDEyNmJjZjM4ZjUwIiwidXNlcl9pZCI6IjMifQ.oBNwgzWFtp5zjAtcY1bwRD_THdHJh8gSDZStGoobDT8

###
GET http://localhost:8000/orders/42e81b2d-a81c-41a5-bd51-0b57ac3b7707/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NzY0NzMzLCJpYXQiOjE3NTk3NjQ0MzMsImp0aSI6ImMwMGNiYjk2MDU4OTRhMTE4NmRiMDk4MDIxZjQzMzI0IiwidXNlcl9pZCI6IjIifQ.GBf2m2UMEmzZ93cdNz425KllDy1HhmFOSe17nNW9XnM